In [11]:
import os
import pandas as pd
import numpy as np

In [3]:
imu_dir = r"C:\Users\ravik\practice\projects\Hand Pose detection\glovedata/"

In [7]:
df = pd.read_csv(imu_dir+"participant_1.csv")
df.head()

,Sensors: lowerArm (0),thumb (1),index (2),mid (3),ring (4),pinky (5),palm (6)
0,Timestamp,Tick,Sensor,QuatI,QuatJ,QuatK,QuatSum
1,0.0,20846,0,0.13577624106523914,-0.6907909948209854,0.7032206062090302,0.0992642576128576
2,0.001,20846,1,-0.5617309101889352,-0.48165278518893523,-0.12088627731106485,-0.6617064961264354
3,0.001,20846,2,-0.7009214369462757,0.4316469224287244,0.08855571429002575,-0.560845753352526
4,0.006,20851,3,-0.5720071173290665,0.5410299920459335,-0.23121553892093338,-0.5715188360790666

In [8]:
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df.head()

,Timestamp,Tick,Sensor,QuatI,QuatJ,QuatK,QuatSum
0,0.0,20846,0,0.13577624106523914,-0.6907909948209854,0.7032206062090302,0.0992642576128576
1,0.001,20846,1,-0.5617309101889352,-0.48165278518893523,-0.12088627731106485,-0.6617064961264354
2,0.001,20846,2,-0.7009214369462757,0.4316469224287244,0.08855571429002575,-0.560845753352526
3,0.006,20851,3,-0.5720071173290665,0.5410299920459335,-0.23121553892093338,-0.5715188360790666
4,0.006,20851,4,-0.6639161395994264,0.3976683330568236,-0.2588743877443235,-0.5779786395994265

In [10]:
preserved_columns = df[['Timestamp',' Sensor']]

In [33]:
# Normalizing quaternions while preserving relationships
def normalize_quaternions(data):
    normalized_quaternions = []
    for _, row in data.iterrows():
        quat = np.array([row[' QuatI'], row[' QuatJ'], row[' QuatK'], row[' QuatSum']])
        norm = np.linalg.norm(quat)  # Calculate magnitude
        normalized_quat = quat / norm # Rescale to unit norm
        normalized_quaternions.append(normalized_quat)
    return pd.DataFrame(normalized_quaternions, columns=['QuatI', 'QuatJ', 'QuatK', 'QuatSum'])

In [34]:
quaternion_cols = [' QuatI',' QuatJ',' QuatK',' QuatSum']

for col in quaternion_cols:
    df[col] = pd.to_numeric(df[col])
    
normalized_quaternions = normalize_quaternions(df)
normalized_quaternions.head()

      QuatI     QuatJ     QuatK   QuatSum
0  0.135776 -0.690791  0.703221  0.099264
1 -0.561731 -0.481653 -0.120886 -0.661706
2 -0.700921  0.431647  0.088556 -0.560846
3 -0.572007  0.541030 -0.231216 -0.571519
4 -0.663916  0.397668 -0.258874 -0.577979

In [35]:
#this is to check if the rescaling is done properly and the relation between quaternions is preserved
data = normalized_quaternions.iloc[10]
print(1 == ((data['QuatI']**2 + data['QuatJ']**2 + data['QuatK']**2 + data['QuatSum']**2)**0.5))

True

In [ ]:
final_data = pd.concat([data[['Timestamp']], normalized_data], axis=1)